-- MySQL Script generated by MySQL Workbench
-- Wed Apr  5 17:01:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema horakj38
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `horakj38`;

-- -----------------------------------------------------
-- Schema horakj38
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horakj38` DEFAULT CHARACTER SET utf8;
USE `horakj38`;

-- -----------------------------------------------------
-- Table `horakj38`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`users`;

CREATE TABLE IF NOT EXISTS `horakj38`.`users`
(
    `id`       INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(64)  NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`decks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`decks`;

CREATE TABLE IF NOT EXISTS `horakj38`.`decks`
(
    `id`   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(256) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`stacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`stacks`;

CREATE TABLE IF NOT EXISTS `horakj38`.`stacks`
(
    `id`       INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`     VARCHAR(256) NOT NULL,
    `decks_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_stacks_decks1_idx` (`decks_id` ASC) VISIBLE,
    CONSTRAINT `fk_stacks_decks1`
        FOREIGN KEY (`decks_id`)
            REFERENCES `horakj38`.`decks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`cards`;

CREATE TABLE IF NOT EXISTS `horakj38`.`cards`
(
    `id`       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `question` VARCHAR(128)    NULL,
    `answer`   VARCHAR(1024)   NULL,
    `decks_id` INT UNSIGNED    NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_cards_decks1_idx` (`decks_id` ASC) VISIBLE,
    CONSTRAINT `fk_cards_decks1`
        FOREIGN KEY (`decks_id`)
            REFERENCES `horakj38`.`decks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`cards_in_stacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`cards_in_stacks`;

CREATE TABLE IF NOT EXISTS `horakj38`.`cards_in_stacks`
(
    `cards_id`  BIGINT UNSIGNED NOT NULL,
    `stacks_id` INT UNSIGNED    NOT NULL,
    PRIMARY KEY (`cards_id`, `stacks_id`),
    INDEX `fk_cards_in_stacks_stacks1_idx` (`stacks_id` ASC) VISIBLE,
    CONSTRAINT `fk_cards_in_stacks_cards1`
        FOREIGN KEY (`cards_id`)
            REFERENCES `horakj38`.`cards` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_cards_in_stacks_stacks1`
        FOREIGN KEY (`stacks_id`)
            REFERENCES `horakj38`.`stacks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`invitation_links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`invitation_links`;

CREATE TABLE IF NOT EXISTS `horakj38`.`invitation_links`
(
    `id`       INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `arg`      CHAR(64)     NOT NULL,
    `expires`  INT UNSIGNED NOT NULL,
    `users_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_invitation_links_users1_idx` (`users_id` ASC) VISIBLE,
    CONSTRAINT `fk_invitation_links_users1`
        FOREIGN KEY (`users_id`)
            REFERENCES `horakj38`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`results`;

CREATE TABLE IF NOT EXISTS `horakj38`.`results`
(
    `id`        INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `fraction`  DOUBLE       NOT NULL,
    `date`      DATETIME     NULL DEFAULT NOW(),
    `users_id`  INT UNSIGNED NOT NULL,
    `stacks_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_results_users1_idx` (`users_id` ASC) VISIBLE,
    INDEX `fk_results_stacks1_idx` (`stacks_id` ASC) VISIBLE,
    CONSTRAINT `fk_results_users1`
        FOREIGN KEY (`users_id`)
            REFERENCES `horakj38`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_results_stacks1`
        FOREIGN KEY (`stacks_id`)
            REFERENCES `horakj38`.`stacks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`privileges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`privileges`;

CREATE TABLE IF NOT EXISTS `horakj38`.`privileges`
(
    `id`       INT UNSIGNED        NOT NULL AUTO_INCREMENT,
    `rank`     TINYINT(1) UNSIGNED NOT NULL,
    `decks_id` INT UNSIGNED        NOT NULL,
    `users_id` INT UNSIGNED        NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_privileges_decks1_idx` (`decks_id` ASC) VISIBLE,
    INDEX `fk_privileges_users1_idx` (`users_id` ASC) VISIBLE,
    CONSTRAINT `fk_privileges_decks1`
        FOREIGN KEY (`decks_id`)
            REFERENCES `horakj38`.`decks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_privileges_users1`
        FOREIGN KEY (`users_id`)
            REFERENCES `horakj38`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`images`;

CREATE TABLE IF NOT EXISTS `horakj38`.`images`
(
    `src` CHAR(10)   NOT NULL,
    `ext` VARCHAR(8) NOT NULL,
    PRIMARY KEY (`src`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`answer_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`answer_images`;

CREATE TABLE IF NOT EXISTS `horakj38`.`answer_images`
(
    `id`         INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    `cards_id`   BIGINT UNSIGNED NOT NULL,
    `images_src` CHAR(10)        NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_answer_images_cards1_idx` (`cards_id` ASC) VISIBLE,
    INDEX `fk_answer_images_images1_idx` (`images_src` ASC) VISIBLE,
    CONSTRAINT `fk_answer_images_cards1`
        FOREIGN KEY (`cards_id`)
            REFERENCES `horakj38`.`cards` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_answer_images_images1`
        FOREIGN KEY (`images_src`)
            REFERENCES `horakj38`.`images` (`src`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakj38`.`question_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakj38`.`question_images`;

CREATE TABLE IF NOT EXISTS `horakj38`.`question_images`
(
    `id`         INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    `cards_id`   BIGINT UNSIGNED NOT NULL,
    `images_src` CHAR(10)        NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_question_images_cards1_idx` (`cards_id` ASC) VISIBLE,
    INDEX `fk_question_images_images1_idx` (`images_src` ASC) VISIBLE,
    CONSTRAINT `fk_question_images_cards1`
        FOREIGN KEY (`cards_id`)
            REFERENCES `horakj38`.`cards` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_question_images_images1`
        FOREIGN KEY (`images_src`)
            REFERENCES `horakj38`.`images` (`src`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
